name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows-x64:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make

      - name: Upload Artifacts for Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows_x64
          path: out/make/zip/win32/x64/*.zip

  windows-arm64:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} (ARM64)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make -- --arch=arm64 --platform=win32

      - name: Upload Artifacts for Windows (ARM64)
        uses: actions/upload-artifact@v3
        with:
          name: windows_arm64
          path: out/make/zip/win32/arm64/*.zip

  linux-x64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make

      - name: Upload Artifacts for Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64
          path: out/make/zip/linux/x64/*.zip

  linux-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} (ARM64)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make -- --arch=arm64 --platform=linux

      - name: Upload Artifacts for Linux (ARM64)
        uses: actions/upload-artifact@v3
        with:
          name: linux_arm64
          path: out/make/zip/linux/arm64/*.zip

  macos-x64:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make

      - name: Upload Artifacts for macOS
        uses: actions/upload-artifact@v3
        with:
          name: macos_x64
          path: out/make/zip/darwin/x64/*.zip

  macos-arm64:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} (ARM64)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make -- --arch=arm64 --platform=darwin

      - name: Upload Artifacts for macOS (ARM64)
        uses: actions/upload-artifact@v3
        with:
          name: macos_arm64
          path: out/make/zip/darwin/arm64/*.zip
