name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make

      - name: Upload Artifacts for Windows
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-windows
          path: D:\a\xvideos-client\xvideos-client\out\make

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make

      - name: Upload Artifacts for Linux
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-linux
          path: /home/runner/work/xvideos-client/xvideos-client/out/make

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make

      - name: Upload Artifacts for macOS
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-macos
          path: /Users/runner/work/xvideos-client/xvideos-client/out/make
